Feat: changes in ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,7 +39,20 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
-            docker stop myapp || true && docker rm myapp || true
-            docker run -d --name myapp -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
+            # Check if Docker exists
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found, installing..."
+              curl -fsSL https://get.docker.com | bash
+              sudo systemctl enable docker
+              sudo systemctl start docker
+              # Add ubuntu user to docker group
+              sudo usermod -aG docker ubuntu
+            else
+              echo "Docker already installed."
+            fi
 
+            # We will always run docker commands with sudo to avoid group membership issues
+            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
+            sudo docker stop myapp || true && sudo docker rm myapp || true
+            sudo docker run -d --name myapp -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
